apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-01-10T12:06:14Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "193"
  uid: 2c1ae0ad-4c61-4eb3-a149-b00a5145df59
spec:
  clusterIP: 100.64.0.1
  clusterIPs:
  - 100.64.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
